# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31c77910d36a97fb713db3616ddef10df9819d72405a6fc8caf0ad3246339aa4ee5583b307f3c0db91c3664f0d6d82d5aebf7d0d1bd3167814dc29e0f666948

test:
  secret_key_base: dc4c8a1b2054122f02eabc16f24130989943b36dc7da6062e48afebe9636e0810ab84ca11fd09f65d4f316c265881e21a43e86cabedfe16482704e02f2676316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
